defaults:
  - _self_
  - bigym_task@_global_: drawer_top_close
  - override hydra/launcher: submitit_local

# task settings
frame_stack: 4
action_repeat: 1
discount: 0.99
# train settings
num_seed_frames: 0
# eval
eval_every_frames: 2500
num_eval_episodes: 25
# snapshot
save_snapshot: false
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 1
batch_size: 256
demo_batch_size: 256
use_relabeling: true
# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: true
use_wandb: false
# experiment
experiment: exp
# agent
lr: 5e-5
weight_decay: 0.1
feature_dim: 64
num_update_steps: 1
use_compile: false

agent:
  _target_: bigym_src.cqn.CQNAgent
  rgb_obs_shape: ??? # to be specified later
  low_dim_obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  weight_decay: ${weight_decay}
  critic_target_tau: 1.0
  critic_target_interval: 50
  update_every_steps: 1
  num_expl_steps: 0
  feature_dim: ${feature_dim}
  hidden_dim: 512
  levels: 3
  bins: 5
  atoms: 51
  v_min: -2.0  # maybe -1.0/1.0?
  v_max: 2.0
  rgb_encoder_layers: 2
  critic_lambda: 0.1
  stddev_schedule: 0.01
  bc_lambda: 1.0
  bc_margin: 0.1

wandb:
  project: cqn
  entity: user
  name: name

hydra:
  run:
    dir: ./exp_local/cqn_bigym/${task_name}_${now:%Y%m%d%H%M%S}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
