defaults:
  - _self_
  - dmc_task@_global_: cartpole_swingup
  - override hydra/launcher: submitit_local

# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: false
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: true
use_wandb: false
# experiment
experiment: exp
# agent
lr: 1e-4
feature_dim: 64
num_update_steps: 1
use_compile: false
use_cuda_graph: false

agent:
  _target_: dmc_src.cqn.CQNAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.02
  critic_target_interval: 1
  update_every_steps: 2
  num_expl_steps: 2000
  feature_dim: ${feature_dim}
  hidden_dim: 512
  levels: 3
  bins: 5
  atoms: 51
  v_min: 0
  v_max: 200
  stddev_schedule: 0.1

wandb:
  project: cqn
  entity: user
  name: name

hydra:
  run:
    dir: ./exp_local/cqn_dmc/${task_name}_${now:%Y%m%d%H%M%S}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
